### ISSUE TITLE
Error in line 132

### ISSUE THREAD

**Issue by fabiocarbone** [corcorana/restingIAF#3]
Error message in EEGLAB 2024.0 (Matlab version 2024a): 
Undefined function "hamming" for input arguments of type "double"
Not working when importing row BDF files (from BioSemi) or preprocessed files (.set) .We use the last version of Matlab (works in older version)

**Comment by corcorana** [comment]
Thank you for flagging this issue. This code pertains to the specification of the taper function used when generating the PSD, where hamming is implemented as the default. It appears from the MATLAB 2024a documentation for `pwelch` that this has not changed, so I wonder if the issue might be due to a conflict with functions in EEGLAB (I have had problems when directly calling `pwelch` with EEGLAB on my path recently). Can you please import your data, remove EEGLAB from the path -- `rmpath(genpath('eeglab2024.0'))` -- and then try running the function ? This will at least rule out one possible cause of the issue.

**Comment by fabiocarbone** [comment]
Hi, thank you for the answer. We could find a solution. The function required some toolboxes in Matlab that we needed to re-install. After doing so the problem was solved. Thanks again. Bye
